### ISSUE TITLE
Windows Security Detected Backdoor:PHP/Yorcirekrikseng.E

### ISSUE THREAD

**Issue by kamsalisbury** [Codiad/Codiad#1115]
In the 12-13-19 download of Codiad-v.2.8.4.zip
![PHP Backdown in Github hosted webapp Codiad-v 2 8 4 zip download](https://user-images.githubusercontent.com/29674098/70822096-b5cd5500-1daa-11ea-8c47-3ff55311cdd0.PNG)
, Windows Security detected Backdoor:PHP/Yorcirekrikseng.E in file components/project/class.project.php

**Comment by ZeCrusher** [comment]
Exactly the same thing, you should no longer use the latest version. I have nothing on the first version of Codiad.

**Comment by cadjou** [comment]
Same for me, and i use the version 2.7.5. Window don't like /components/project/class.project.php

**Comment by HLSiira** [comment]
**Summary:** I'm trying to maintain my own fork of codiad and address all open issues. As far as I can tell, these are false flags and you can ignore them in my decidedly non-security expert opinion. If it was a vulnerability, I'd be worried, but Microsoft thinks it's malicious code and it just doesn't appear to be the case looking into it, but I'm just some random dude on the internet.


**Explanation:**
I'm trying to maintain and upgrade my own fork of Codiad since I love it so much and as such, am trying to address the open issues in the Codiad Repo.

Now I am not a security expert and I'm still trying to figure this out, but my guess is that it's a false flag, but it's entirely possible that I am wrong. Here's what I did:

Using VirusTotal.com, I uploaded various previous versions of class.project.php and had them scanned. I kept going further and further back until I found a "clean" version of the file, and worked from there until I found the first commit that it pinged on. Keep in mind, I only ever copied the code from Github, I did not use the actual file, so I don't think there is a possibility of there being hidden code in some sort of metadata/tag.

This is the last clean file I could find: [Commit on 2013JAN16 by amontero](https://www.virustotal.com/gui/file/70f10beca6a8d4a4604405b1dcf500c39a1016b8395d0db2ae52fb97978b17a3/detection)
Then first bad file: [Commit on 2013MAR02](https://www.virustotal.com/gui/file/a3a7b9c15d124d147f00b0a9bd677b7e5f239dfb4b84cd32e5bd6b241ab0d05f/detection)

Looking at the code, there is nothing that really sticks out to me as malicious or even useful, but I continued. If I was Windows, maybe I think ExecuteCommand is evil, so I deleted that function, and reuploaded it. Well now I have a different message, a Trojan instead of a backdoor.

Alright, so I uploaded the Execute Command function in it's own PHP file, and I was told it contained the **Yorcirekrikseng** backdoor.

I continued onward. Overall I found two functions that were causing issues:
1. ExecuteCommand as a backdoor,
2. Delete as a Trojan

I managed to remove the falseflag on the execute command by removing a small portion of the Execute function. It tries to execute the command through 4 different methods, if any of them exist. The first two seem to stream back data straight to the client and that might make Microsoft think they're bad. Based on my reading, the two I left over seem fine, but I don't see how either of the four can be used maliciously since they only input given to them is mostly hard coded, and then cleaned/sanitized via php escapeshellarg functions in the create project function above.

The delete function on the other hand seems to be a hit or miss on if it thinks it's a Trojan or not, and more often it's not.


I'm going to leave the code as it is in my own distribution because I don't see how it could be malicious, all the code seems purpose built to accomplish the various tasks associated with having multiple projects.

Hope this helps.
