### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by LRoffic** [Codiad/Codiad#562]
Hello! I just made the last update and it deleted the Moitier my file. She has not touched my workspace!

**Comment by megadr01d** [comment]
This issue still persists. No auto-update plugin installed.

- I check for updates

Your version: 2.6.0
Latest Version: 2.6.4

- I click cancel and check for updates

Your version: 2.6.0
Latest Version: 2.6.4
(OK)

- I click cancel, check for updates again and click download
- Download starts
- I check for updates

Your version: (blank)
Latest Version: 2.6.4

- I refresh the page and check for updates

Your version: 2.6.4
Latest Version: 2.6.4
(Not OK - I'm still running 2.6.0 but it gets identified as 2.6.4)

**Comment by daeks** [comment]
it is not really an issue. It is more or less intented behaviour, as there is no ideal way to trigger a manual update. So on each "download", Codiad assume that there will be an update and resets the version file

**Comment by megadr01d** [comment]
I'm just finding hard to understand this assumption logic. If after I download it, I find out that it has some new bugs and revert back to 2.6.0 or an even older version, Codiad will always tell me I'm on the latest version because it assumed I wanted to use the latest version.

Codiad knew that I'm running v2.6.0. Does it read it from `data/version.php`? Shouldn't the version be part of the package, eg. `<install folder>/version.php` and not part of the user data folder? When manually installing a new version and migrating the old user folder, the correct version would always be read from `<install folder>/version.php`.

**Comment by daeks** [comment]
Yeah the logic is quite ugly, but yes it is reading the version from data/version.php cause nobody wanted to store versioning information in the package itself in the past. If i remember correctly, the reason was the requirement to manually change the version on each release.

**Comment by megadr01d** [comment]
OK, then maybe Codiad shouldn't display the current version, since it can't guess it correctly anyway, and just display if there's a new version or not.

**Comment by daeks** [comment]
I am happy to see your propose as pull request
