### ISSUE TITLE
Autologin?

### ISSUE THREAD

**Issue by RDaneelOlivav** [Codiad/Codiad#851]
How could it be done? Is it possible to create the user only once and then configure it in a manner that when starting Codiad every time it enters automatically without sign-in page?

**Comment by dugite-code** [comment]
1.   You could use the External authentication [http auth](https://gist.github.com/basteln3rk/4cab14ebd990e46efaef#file-codiad_http_auth-php) set up your .htaccess file and then just bookmark your link as user:pass@localhost`

2. Use your webserver to pass the php_authors header instead of the simple bookmark

3. you could (very very very very insecurely) use:

```
<?php
if (!isset($_SESSION['user'])) {
	require_once( COMPONENTS . "/user/class.user.php" );
	$_SESSION['user'] = 'username'
}
```

At least I think that should work, I haven't given it a test myself yet as I'm not at my computer

**Comment by smolinari** [comment]
I haven't looked where it is, but I am sure Codiad sets a cookie with a fairly short cookie timeout (TTL) period (probably 15 minutes). Find where this is set and just extend the time to something a lot longer. Then, when you enter Codiad from the same browser, you will be logged in automatically again.

Scott

**Comment by daeks** [comment]
Changing the timeout of the cookie will not help, as we are looking for session variables

https://github.com/Codiad/Codiad/blob/master/index.php#L110

So at least you have to modify this "if" statement and provide a functionally to reinit the user session

https://github.com/Codiad/Codiad/blob/master/components/user/class.user.php#L43

**Comment by smolinari** [comment]
Thanks for the clarification and correction daeks. :+1: 

Scott
