### ISSUE TITLE
Problems while writing code

### ISSUE THREAD

**Issue by fabricebsi** [Codiad/Codiad#872]
Hi everyone,

I have a similar problem to this topic #516 
Regularly, the text is changed and the characters are mixed while writing.
For example, we put an echo in the php file, we save and when we reload the file, the characters are totally mixed.
We no longer use the collaborative mode. 
We tried to clear all the cache, logout, login but the problem persists.
Yesterday we have trouble in saving and we had to delete the user and create a new one.

We have the latest version of codiad.

Does anyone have an idea to solve the problem?

Thnaks

**Comment by Korynkai** [comment]
Seems to be a common problem. This was occurring on my setup as well (for a good long time in fact... however our group was on a development hiatus while other business was being addressed, so it wasn't reported by anyone in our group until recently). 

After some searching and experimentation, it looks as if this is an issue with Codiad's version of the ACE editor. After dropping in the latest ACE editor from https://github.com/ajaxorg/ace-builds (/src-min-noconflict -> /components/editor/ace-editor), this problem seems to have disappeared. Can anybody confirm this?

**Comment by daeks** [comment]
Currently I am unable to confirm that, but nevertheless I am happy to see an ACE upgrade pull request anyway.

**Comment by daeks** [comment]
Codiad has updated its internal editor which should resolve this issue. Please check it and state your result at #516
