### ISSUE TITLE
How can I close the registration?

### ISSUE THREAD

**Issue by alexandrmint** [Codiad/Codiad#888]
I want to close the registation new users. How i can do it?

**Comment by Korynkai** [comment]
@alexandrmint: Codiad's registration is private by design. Only the first user registration is what would be called an "open" registration and any subsequent registration goes through any users already registered using the Users option under Administration in the Menu Sidebar.

If you are looking to handle authentication using an external mechanism, I suggest the following page: https://github.com/Codiad/Codiad/wiki/External-Auth. Please note, regardless of the External-Auth scheme used (if you choose to use this), _the user must also exist in the `/data/users.php` file_ (however in the case of External Auth, the password may be set to null). If registration itself is managed by some external means, this file must be handled by the registration mechanism.

Regardless, after the initial user is created, there is no _internal_ mechanism within Codiad for handling public registration.
