### ISSUE TITLE
Login Button not working

### ISSUE THREAD

**Issue by wazahm** [Codiad/Codiad#890]
I just uploaded Codiad in [my website](http://inc.xtnote.com). After the setup/installation page, login window appeared. I typed the username and the password which I was mention in the setup page. **The problem is, when I click the Login button, nothing happened**. I checked the code for the button through the browser's "Inspect Element" option. It seems like no code is written for the Login button.

**Comment by daeks** [comment]
The login is done with javascript (https://github.com/Codiad/Codiad/blob/master/components/user/init.js#L27).

Is there any output from your browser? javascript enabled? which browser.. etc

**Comment by nickgs** [comment]
I just had the same issue. Codiad was working fine in Chrome, Firefox, and Safari BUT IE 11 would just refresh the page (line 70 in user/init.js). After some digging it became apparent that a new session was being recreated on each request. 

The issue was that I had underscores in my domain. According to the RFCs underscores are not valid characters to have in domains. It seems  the way IE handles this is to just silently drop the session cookie. 

I took the underscore out of my domain and Codiad starting working well. 

I do not see invalid characters in your domain so I am not sure if this directly correlates to this issue. I would investigate further on how sessions are being handled in your environment.

**Comment by mitchas** [comment]
So besides the underscore domain fix @nickgs used, has anyone else had this problem? For me, after setup and initial installation, when I click login it just refreshes the login page.

When I click the "More" button nothing happens.

It seems like there's just no Javascript firing.
